/* tslint:disable */
/* eslint-disable */
/**
 * Goal API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface Goal
 */
export interface Goal {
    /**
     * 
     * @type {number}
     * @memberof Goal
     */
    id?: number;
    /**
     * 
     * @type {Date}
     * @memberof Goal
     */
    timestamp?: Date;
    /**
     * 
     * @type {string}
     * @memberof Goal
     */
    description?: string | null;
}

export function GoalFromJSON(json: any): Goal {
    return GoalFromJSONTyped(json, false);
}

export function GoalFromJSONTyped(json: any, ignoreDiscriminator: boolean): Goal {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'id': !exists(json, 'id') ? undefined : json['id'],
        'timestamp': !exists(json, 'timestamp') ? undefined : (new Date(json['timestamp'])),
        'description': !exists(json, 'description') ? undefined : json['description'],
    };
}

export function GoalToJSON(value?: Goal | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'id': value.id,
        'timestamp': value.timestamp === undefined ? undefined : (value.timestamp.toISOString()),
        'description': value.description,
    };
}


