/* tslint:disable */
/* eslint-disable */
/**
 * Goal API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface PostGoal
 */
export interface PostGoal {
    /**
     * 
     * @type {string}
     * @memberof PostGoal
     */
    description: string;
}

export function PostGoalFromJSON(json: any): PostGoal {
    return PostGoalFromJSONTyped(json, false);
}

export function PostGoalFromJSONTyped(json: any, ignoreDiscriminator: boolean): PostGoal {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'description': json['description'],
    };
}

export function PostGoalToJSON(value?: PostGoal | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'description': value.description,
    };
}


