import * as React from 'react';
import * as ReactDom from 'react-dom';
import * as autogenerated from '../autogenerated';
import { Configuration } from '../autogenerated';
let api = new autogenerated.GoalsApi(
    new Configuration({
        basePath:"https://goal-api.azurewebsites.net"
    })
);

api.api1GoalsGet().then((e)=>
{
    console.log(e);
});


if('serviceWorker' in navigator) 
{
    navigator.serviceWorker
    .register('./sw.ts')
    .then(function() { console.log('Service Worker Registered'); });
}

const Index = ()=>
{


    return <div>hello world!</div>
}


ReactDom.render(<Index/>, document.getElementById("main"));