Remove-Item ./autogenerated/* -Recurse
docker run --rm -it -v ${pwd}:/root -v ${pwd}/autogenerated:/out/src/Org.OpenAPITools `
openapitools/openapi-generator-cli generate -o /out -i http://host.docker.internal:5000/swagger/v1/swagger.json -g csharp-netcore
Remove-Item ./autogenerated/*.csproj -Recurse
Remove-Item ./autogenerated/*.json -Recurse
Remove-Item ./autogenerated/Properties -Force -Recurse