name: .NET Core CI
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.100
    - name: Publish Goal.Server
      run: |
        export VERSION=$($(date +%Y).$(date +%m).$(date +%d).$(date +%H)$(date +%M))
        echo $VERSION
        cd Goal.Server
        dotnet publish --configuration Release --output ./output /p:Version="$VERSION"
    - name: Deploy Web App
      uses: Azure/webapps-deploy@v1
      with:
        publish-profile: ${{secrets.PUBLISH_PROFILE_APP}}
        app-name: ${{secrets.AZURE_WEBAPP_NAME}}
        package: ./Goal.Server/output
