name: .NET Core Tag

on:
  release:
    types: [published]
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: ./github/actions/setup
    - name: Pack Goal and Push
      run: |
        cd Goal
        dotnet pack --configuration Release
        dotnet nuget push nuget/*.nupkg -s https://www.nuget.org -k ${{secrets.NUGET_KEY}}
